package dev.aidanbehar.nuclearstation.sim;

/**
 * Control-room annunciator windows. Priority 1 = red (immediate action), 2 = amber
 * (prompt action), 3 = white (advisory). The category distinguishes real process
 * conditions from equipment faults and from instrumentation problems.
 */
public enum AlarmId {
	REACTOR_TRIP("REACTOR TRIP", 1, Category.PROTECTION),
	SI_ACTUATED("SAFETY INJECTION ACTUATED", 1, Category.PROTECTION),
	HIGH_FLUX("NEUTRON FLUX HIGH", 1, Category.PROCESS),
	HIGH_STARTUP_RATE("STARTUP RATE HIGH", 2, Category.PROCESS),
	PZR_PRESS_HIGH("PRZR PRESSURE HIGH", 2, Category.PROCESS),
	PZR_PRESS_LOW("PRZR PRESSURE LOW", 2, Category.PROCESS),
	PZR_LEVEL_HIGH("PRZR LEVEL HIGH", 3, Category.PROCESS),
	PZR_LEVEL_LOW("PRZR LEVEL LOW", 2, Category.PROCESS),
	PORV_OPEN("PRZR PORV OPEN", 2, Category.PROCESS),
	SUBCOOLING_LOW("RCS SUBCOOLING MARGIN LOW", 1, Category.PROCESS),
	RCS_FLOW_LOW("RCS FLOW LOW", 1, Category.PROCESS),
	RCS_LEAK("RCS LEAKAGE ABNORMAL", 2, Category.PROCESS),
	TAVG_DEVIATION("TAVG/TREF DEVIATION", 3, Category.PROCESS),
	DNB_MARGIN_LOW("DNB MARGIN LOW", 1, Category.PROCESS),
	CORE_EXIT_TEMP_HIGH("CORE EXIT TEMPERATURE HIGH", 1, Category.PROCESS),
	CORE_DAMAGE("CORE DAMAGE INDICATED", 1, Category.PROCESS),
	SG_LEVEL_LOW("SG LEVEL LOW", 2, Category.PROCESS),
	SG_LEVEL_HIGH("SG LEVEL HIGH", 2, Category.PROCESS),
	SG_PRESSURE_HIGH("SG PRESSURE HIGH", 3, Category.PROCESS),
	FEED_FLOW_LOSS("FEEDWATER FLOW LOST", 1, Category.PROCESS),
	CST_LEVEL_LOW("CONDENSATE STORAGE TANK LOW", 2, Category.PROCESS),
	TURBINE_TRIP("TURBINE TRIP", 2, Category.PROTECTION),
	TURBINE_OVERSPEED("TURBINE OVERSPEED", 1, Category.PROCESS),
	TURBINE_VIBRATION("TURBINE VIBRATION HIGH", 2, Category.EQUIPMENT),
	CONDENSER_VACUUM_LOW("CONDENSER VACUUM LOW", 2, Category.PROCESS),
	DISCHARGE_TEMP_HIGH("CW DISCHARGE TEMP HIGH", 3, Category.PROCESS),
	INTAKE_SCREEN_DP("INTAKE SCREEN DIFF PRESS HIGH", 3, Category.EQUIPMENT),
	GEN_BREAKER_OPEN("GENERATOR BREAKER OPEN", 3, Category.PROCESS),
	GRID_LOST("OFFSITE POWER LOST", 1, Category.PROCESS),
	STATION_BLACKOUT("STATION BLACKOUT", 1, Category.PROCESS),
	BUS_DEAD("BUS UNDERVOLTAGE", 2, Category.PROCESS),
	EDG_RUNNING("DIESEL GENERATOR RUNNING", 3, Category.PROCESS),
	EDG_OVERLOAD("DIESEL GENERATOR OVERLOAD", 2, Category.PROCESS),
	BATTERY_DISCHARGING("BATTERY DISCHARGING", 2, Category.PROCESS),
	BATTERY_LOW("BATTERY VOLTAGE LOW", 1, Category.PROCESS),
	TRANSFORMER_TEMP_HIGH("MAIN TRANSFORMER TEMP HIGH", 2, Category.EQUIPMENT),
	EQUIPMENT_FAILURE("EQUIPMENT FAILURE", 2, Category.EQUIPMENT),
	CHANNEL_DEVIATION("INSTRUMENT CHANNEL DEVIATION", 3, Category.INSTRUMENT),
	CHANNEL_FAILED("PROTECTION CHANNEL FAILED", 2, Category.INSTRUMENT),
	CONT_PRESS_HIGH("CONTAINMENT PRESSURE HIGH", 1, Category.PROCESS),
	CONT_HYDROGEN_HIGH("CONTAINMENT HYDROGEN HIGH", 1, Category.PROCESS),
	CONT_RADIATION_HIGH("CONTAINMENT RADIATION HIGH", 1, Category.PROCESS),
	CONTAINMENT_BREACH("CONTAINMENT INTEGRITY LOST", 1, Category.PROCESS),
	OFFSITE_RELEASE("RADIOACTIVE RELEASE IN PROGRESS", 1, Category.PROCESS),
	RWST_LOW("RWST LEVEL LOW - SWAP TO RECIRC", 1, Category.PROCESS),
	SFP_TEMP_HIGH("SPENT FUEL POOL TEMP HIGH", 2, Category.PROCESS),
	SFP_LEVEL_LOW("SPENT FUEL POOL LEVEL LOW", 1, Category.PROCESS),
	XENON_TRANSIENT("XENON TRANSIENT IN PROGRESS", 3, Category.PROCESS),
	ROD_WITHDRAWAL_BLOCK("ROD WITHDRAWAL BLOCKED", 3, Category.PROTECTION),
	DECAY_HEAT_REMOVAL_LOST("DECAY HEAT REMOVAL INADEQUATE", 1, Category.PROCESS);

	public final String text;
	public final int priority;
	public final Category category;

	AlarmId(String text, int priority, Category category) {
		this.text = text;
		this.priority = priority;
		this.category = category;
	}

	public enum Category {
		PROCESS, EQUIPMENT, INSTRUMENT, PROTECTION
	}
}
