package dev.aidanbehar.nuclearstation.sim;

/** Every numeric plant parameter exported to the control-room interface. */
public enum Readout {
	SIM_TIME("Plant time", "s", "%.0f"),
	NEUTRON_POWER("Neutron power", "%", "%.2f"),
	THERMAL_POWER("Core thermal power", "MWt", "%.0f"),
	DECAY_HEAT("Decay heat", "MWt", "%.1f"),
	STARTUP_RATE("Startup rate", "DPM", "%.2f"),
	LOG_POWER("Log power", "decades", "%.2f"),
	REACTIVITY("Total reactivity", "pcm", "%.0f"),
	RHO_RODS("Rod worth inserted", "pcm", "%.0f"),
	RHO_BORON("Boron reactivity", "pcm", "%.0f"),
	RHO_DOPPLER("Doppler (fuel temp)", "pcm", "%.0f"),
	RHO_MODERATOR("Moderator temp/void", "pcm", "%.0f"),
	RHO_XENON("Xenon-135", "pcm", "%.0f"),
	RHO_FUEL("Fuel excess", "pcm", "%.0f"),
	MTC("Moderator temp coeff", "pcm/K", "%.1f"),
	BORON("RCS boron", "ppm", "%.0f"),
	BORON_TARGET("Boron target", "ppm", "%.0f"),
	XENON("Xenon (rel. to eq.)", "", "%.2f"),
	IODINE("Iodine-135 (rel.)", "", "%.2f"),
	BURNUP("Cycle burnup", "%", "%.1f"),
	SHUTDOWN_BANKS("Shutdown banks", "steps", "%.0f"),
	CONTROL_GROUP("Control group", "steps", "%.0f"),
	BANK_A("Bank A", "steps", "%.0f"),
	BANK_B("Bank B", "steps", "%.0f"),
	BANK_C("Bank C", "steps", "%.0f"),
	BANK_D("Bank D", "steps", "%.0f"),
	FUEL_TEMP("Fuel avg temp", "C", "%.0f"),
	PEAK_CLAD("Peak clad temp", "C", "%.0f"),
	DNBR("DNB ratio", "", "%.2f"),
	T_HOT("Thot", "C", "%.1f"),
	T_COLD("Tcold", "C", "%.1f"),
	T_AVG("Tavg", "C", "%.1f"),
	T_REF("Tref", "C", "%.1f"),
	RCS_PRESSURE("Pressurizer pressure", "MPa", "%.2f"),
	PZR_LEVEL("Pressurizer level", "%", "%.1f"),
	PZR_HEATERS("Heater output", "MW", "%.2f"),
	PZR_SPRAY("Spray demand", "%", "%.0f"),
	SUBCOOLING("Subcooling margin", "K", "%.1f"),
	RCS_FLOW("RCS flow", "%", "%.1f"),
	RCS_INVENTORY("RCS inventory", "%", "%.1f"),
	VOID_FRACTION("Core void fraction", "%", "%.1f"),
	CORE_COVERED("Core collapsed level", "%", "%.0f"),
	CHARGING("Charging flow", "kg/s", "%.1f"),
	SI_FLOW("Injection flow", "kg/s", "%.0f"),
	LEAK_FLOW("Unidentified leakage", "kg/s", "%.1f"),
	RWST("RWST level", "%", "%.0f"),
	ACCUMULATORS("Accumulators", "%", "%.0f"),
	SUMP("Containment sump", "t", "%.0f"),
	SG_PRESSURE("SG pressure", "MPa", "%.2f"),
	SG_LEVEL_NR("SG level (NR)", "%", "%.1f"),
	SG_LEVEL_WR("SG level (WR)", "%", "%.1f"),
	STEAM_TURBINE("Steam to turbine", "kg/s", "%.0f"),
	STEAM_DUMP("Steam dump flow", "kg/s", "%.0f"),
	STEAM_ADV("Atmospheric relief", "kg/s", "%.0f"),
	FEED_FLOW("Feedwater flow", "kg/s", "%.0f"),
	MFW_FLOW("Main feed flow", "kg/s", "%.0f"),
	AFW_FLOW("Aux feed flow", "kg/s", "%.0f"),
	FEED_TEMP("Feedwater temp", "C", "%.0f"),
	CST("Condensate storage", "%", "%.0f"),
	ADV_POSITION("ADV position", "%", "%.0f"),
	TURBINE_SPEED("Turbine speed", "rpm", "%.0f"),
	SPEED_SETPOINT("Speed setpoint", "rpm", "%.0f"),
	GOVERNOR("Governor valves", "%", "%.1f"),
	TURBINE_MECH("Turbine shaft power", "MW", "%.0f"),
	GENERATOR("Generator output", "MWe", "%.0f"),
	LOAD_SETPOINT("Load setpoint", "MWe", "%.0f"),
	LOAD_RAMPED("Load reference", "MWe", "%.0f"),
	RAMP_RATE("Ramp rate", "MW/min", "%.0f"),
	HOUSE_LOAD("House load", "MWe", "%.1f"),
	NET_OUTPUT("Net to grid", "MWe", "%.0f"),
	GRID_DEMAND("Dispatch request", "MWe", "%.0f"),
	VIBRATION("Turbine vibration", "um", "%.0f"),
	GSU_TEMP("Main transformer oil", "C", "%.0f"),
	CONDENSER_PRESSURE("Condenser pressure", "kPa", "%.1f"),
	CONDENSER_TEMP("Condenser temp", "C", "%.1f"),
	CW_FLOW("Circulating water", "%", "%.0f"),
	CW_OUTLET("CW outlet temp", "C", "%.1f"),
	DISCHARGE_TEMP("Discharge to sea", "C", "%.1f"),
	SEA_TEMP("Intake (sea) temp", "C", "%.1f"),
	TOWER_HEAT("Tower heat rejection", "MW", "%.0f"),
	SCREEN_FOULING("Intake screen fouling", "%", "%.0f"),
	BUS_NS1_LOAD("NS-1 load", "MW", "%.1f"),
	BUS_NS2_LOAD("NS-2 load", "MW", "%.1f"),
	BUS_SA_LOAD("Safety A load", "MW", "%.1f"),
	BUS_SB_LOAD("Safety B load", "MW", "%.1f"),
	EDG_A_FUEL("EDG A fuel", "%", "%.0f"),
	EDG_B_FUEL("EDG B fuel", "%", "%.0f"),
	EDG_A_TIMER("EDG A start", "s", "%.0f"),
	EDG_B_TIMER("EDG B start", "s", "%.0f"),
	BATTERY_A("Battery A charge", "%", "%.0f"),
	BATTERY_B("Battery B charge", "%", "%.0f"),
	CONT_PRESSURE("Containment pressure", "kPa", "%.0f"),
	CONT_TEMP("Containment temp", "C", "%.0f"),
	CONT_HYDROGEN("Containment hydrogen", "%", "%.2f"),
	CONT_INTEGRITY("Containment integrity", "%", "%.0f"),
	CONT_DOSE("Containment dose rate", "Sv/h", "%.3g"),
	AIRBORNE("Airborne activity", "% core", "%.3g"),
	RELEASE_RATE("Release rate", "%/h", "%.3g"),
	RELEASE_TOTAL("Total release", "% core", "%.3g"),
	OXIDATION("Cladding oxidised", "%", "%.1f"),
	HYDROGEN_MASS("Hydrogen generated", "kg", "%.0f"),
	CORE_DAMAGE("Core damage", "%", "%.1f"),
	CORE_MELT("Core melt", "%", "%.1f"),
	LOWER_HEAD_TEMP("Lower head temp", "C", "%.0f"),
	BASEMAT_EROSION("Basemat erosion", "m", "%.2f"),
	SFP_TEMP("Spent fuel pool temp", "C", "%.1f"),
	SFP_LEVEL("Spent fuel pool level", "%", "%.0f"),
	CCW_TEMP("CCW temperature", "C", "%.1f");

	public final String label;
	public final String unit;
	public final String format;

	Readout(String label, String unit, String format) {
		this.label = label;
		this.unit = unit;
		this.format = format;
	}

	public String format(double v) {
		if (Double.isNaN(v)) {
			return "----";
		}
		return String.format(format, v);
	}
}
